---
procfwk:
  vm:
    hostname: 'procfwk.jumbo.dlt.dev.local'
    box: 'dgroen/procfwk'
    cpus: 4
    mem: 16384
    user: 'ubuntu'
    host_ssh_port: 3326
    natnet: 'VSLabNet'
    natnet_cidr: '10.3/16'
  ssh_config: 
    username: 'vagrant'
    password: 'vagrant'
    insert_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key'
  network:
    ip: '192.168.33.10'
    domain: 'jumbo.dlt.dev.local'
  secrets:
    ssh_key_files: '/vagrant/secrets/ssh/procfwk'
  scripts:
    pre_process: './scripts/pre-process.sh'
    post_process: './scripts/post-process.sh'
    ssh_keygen: './scripts/ssh-keygen.sh'
  config_files: './config/'
  mounts:
    vm_secrets:
      host_path: './secrets'
      guest_path: '/tmp/secrets'
    vm_config:
      host_path: './config'
      guest_path: '/opt/vm_config'
    scripts:
      host_path: './scripts'
      guest_path: '/opt/vm_scripts'
    vagrant:
      host_path: '.'
      guest_path: '/vagrant'
    data:
      host_path: 'C:\Users\WMEIJS\JumboRepos'
      guest_path: '/Data/DLT'
  provision_script_file: './provisioner.sh'
  services:
    dns:
      type: 'client'
      nameserver1:
        name: ns1
        domain: jumbo.dlt.dev.local
        ip: 8.8.8.8
        interfaces: 'eth0 eth1'
      nameserver2:
        name: ns2
        domain: jumbo.dlt.dev.local
        ip: 8.8.4.4
        interfaces: 'eth0 eth1'
    desktop:
      type: 'xfce'
      cmd: 'sudo apt install xfce4'
