# Vagrantfile for a lightweight VM
Vagrant.configure("2") do |config|
    # Use a lightweight Ubuntu 18.04 box
    config.vm.box = "bento/ubuntu-22.04" # Ubuntu 22.04 Server
  
    # Set the VM hostname
    config.vm.hostname = "lightweight-vm"
  
    # Customize the VM resources
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "8192" # Allocate 512 MB of RAM
      vb.cpus = 4       # Allocate 1 CPU
      vb.name = "lightweight-vm" # Name of the VM in VirtualBox
    end

    # Optional: Provision with a simple shell script
    config.vm.provision "shell", path: "test.sh"

  # Provision to copy your local gitconfig file to your virtual machine
  config.vm.provision "file", source: "~/.gitconfig", destination: "~/.gitconfig"
  end
  