# Vagrantfile for a lightweight VM
Vagrant.configure("2") do |config|
    # Use a lightweight Ubuntu 18.04 box
    config.vm.box = "hashicorp/bionic64"
  
    # Set the VM hostname
    config.vm.hostname = "lightweight-vm"
  
    # Customize the VM resources
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512" # Allocate 512 MB of RAM
      vb.cpus = 1       # Allocate 1 CPU
      vb.name = "LightweightVM" # Name of the VM in VirtualBox
    end
  
    # Sync folder from host to guest (disabled for minimal overhead)
    config.vm.synced_folder ".", "/vagrant", disabled: true
  
    # Optional: Provision with a simple shell script
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt update && sudo apt install -y build-essential git curl
    SHELL
  end
  