FROM python:alpine
RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo make
RUN pip install --upgrade pip 
RUN pip install azure-cli
RUN cd /tmp
RUN wget https://curl.se/download/curl-7.58.0.zip
RUN unzip curl-7.58.0.zip && cd curl-7.58.0
RUN ./configure --prefix=$HOME/curl
RUN make && make install
RUN export PATH=$HOME/curl/bin:$PATH
CMD sh